//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Magazyn.Model
{

    [OptimisticLocking(true)]
    public partial class AsocPzWz : XPLiteObject
    {
        int fId;
        [Key(true)]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>(nameof(Id), ref fId, value); }
        }
        PZ fPZ;
        public PZ PZ
        {
            get { return fPZ; }
            set { SetPropertyValue<PZ>(nameof(PZ), ref fPZ, value); }
        }
        WZ fWZ;
        public WZ WZ
        {
            get { return fWZ; }
            set { SetPropertyValue<WZ>(nameof(WZ), ref fWZ, value); }
        }
    }

}
