//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Magazyn.Model
{

    [OptimisticLocking(true)]
    public partial class Bela : XPLiteObject
    {
        int fId;
        [Key(true)]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>(nameof(Id), ref fId, value); }
        }
        string fKodKreskowy;
        public string KodKreskowy
        {
            get { return fKodKreskowy; }
            set { SetPropertyValue<string>(nameof(KodKreskowy), ref fKodKreskowy, value); }
        }
        Material fMaterial;
        public Material Material
        {
            get { return fMaterial; }
            set { SetPropertyValue<Material>(nameof(Material), ref fMaterial, value); }
        }
        decimal fSzerokosc;
        public decimal Szerokosc
        {
            get { return fSzerokosc; }
            set { SetPropertyValue<decimal>(nameof(Szerokosc), ref fSzerokosc, value); }
        }
        decimal fDlugosc;
        public decimal Dlugosc
        {
            get { return fDlugosc; }
            set { SetPropertyValue<decimal>(nameof(Dlugosc), ref fDlugosc, value); }
        }
        Bela fBelaNadrzedna;
        public Bela BelaNadrzedna
        {
            get { return fBelaNadrzedna; }
            set { SetPropertyValue<Bela>(nameof(BelaNadrzedna), ref fBelaNadrzedna, value); }
        }
        DateTime fDataDodania;
        public DateTime DataDodania
        {
            get { return fDataDodania; }
            set { SetPropertyValue<DateTime>(nameof(DataDodania), ref fDataDodania, value); }
        }
        bool fUkonczona;
        public bool Ukonczona
        {
            get { return fUkonczona; }
            set { SetPropertyValue<bool>(nameof(Ukonczona), ref fUkonczona, value); }
        }
        [Association(@"WZReferencesBela"), Aggregated]
        public XPCollection<WZ> WZs { get { return GetCollection<WZ>(nameof(WZs)); } }
    }

}
