//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Magazyn.Model
{

    [OptimisticLocking(true)]
    public partial class Bledy : XPLiteObject
    {
        int fId;
        [Key(true)]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>(nameof(Id), ref fId, value); }
        }
        DateTime fData;
        public DateTime Data
        {
            get { return fData; }
            set { SetPropertyValue<DateTime>(nameof(Data), ref fData, value); }
        }
        string fTresc;
        [Size(SizeAttribute.Unlimited)]
        public string Tresc
        {
            get { return fTresc; }
            set { SetPropertyValue<string>(nameof(Tresc), ref fTresc, value); }
        }
        string fWersjaProgramu;
        public string WersjaProgramu
        {
            get { return fWersjaProgramu; }
            set { SetPropertyValue<string>(nameof(WersjaProgramu), ref fWersjaProgramu, value); }
        }
    }

}
