//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Magazyn.Model
{

    [OptimisticLocking(true)]
    public partial class ProduktPoduszka : XPLiteObject
    {
        int fId;
        [Key(true)]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>(nameof(Id), ref fId, value); }
        }
        Uzytkownicy fUzytkownik;
        public Uzytkownicy Uzytkownik
        {
            get { return fUzytkownik; }
            set { SetPropertyValue<Uzytkownicy>(nameof(Uzytkownik), ref fUzytkownik, value); }
        }
        Wykroj fWykroj;
        public Wykroj Wykroj
        {
            get { return fWykroj; }
            set { SetPropertyValue<Wykroj>(nameof(Wykroj), ref fWykroj, value); }
        }
        Material fMaterial;
        public Material Material
        {
            get { return fMaterial; }
            set { SetPropertyValue<Material>(nameof(Material), ref fMaterial, value); }
        }
        int fIlosc;
        public int Ilosc
        {
            get { return fIlosc; }
            set { SetPropertyValue<int>(nameof(Ilosc), ref fIlosc, value); }
        }
        int fIloscUszkodzonych;
        public int IloscUszkodzonych
        {
            get { return fIloscUszkodzonych; }
            set { SetPropertyValue<int>(nameof(IloscUszkodzonych), ref fIloscUszkodzonych, value); }
        }
        DateTime fData;
        public DateTime Data
        {
            get { return fData; }
            set { SetPropertyValue<DateTime>(nameof(Data), ref fData, value); }
        }
    }

}
