//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Magazyn.Model
{

    [OptimisticLocking(true)]
    public partial class PZ : XPLiteObject
    {
        int fId;
        [Key(true)]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>(nameof(Id), ref fId, value); }
        }
        Uzytkownicy fUzytkownik;
        public Uzytkownicy Uzytkownik
        {
            get { return fUzytkownik; }
            set { SetPropertyValue<Uzytkownicy>(nameof(Uzytkownik), ref fUzytkownik, value); }
        }
        DateTime fData;
        public DateTime Data
        {
            get { return fData; }
            set { SetPropertyValue<DateTime>(nameof(Data), ref fData, value); }
        }
        decimal fZwrotMaterial;
        public decimal ZwrotMaterial
        {
            get { return fZwrotMaterial; }
            set { SetPropertyValue<decimal>(nameof(ZwrotMaterial), ref fZwrotMaterial, value); }
        }
        decimal fUszkodzonyMaterial;
        public decimal UszkodzonyMaterial
        {
            get { return fUszkodzonyMaterial; }
            set { SetPropertyValue<decimal>(nameof(UszkodzonyMaterial), ref fUszkodzonyMaterial, value); }
        }
        string fUwagi;
        [Size(SizeAttribute.Unlimited)]
        public string Uwagi
        {
            get { return fUwagi; }
            set { SetPropertyValue<string>(nameof(Uwagi), ref fUwagi, value); }
        }
        [Association(@"ProduktWykrojReferencesPZ"), Aggregated]
        public XPCollection<ProduktWykroj> ProduktWykrojs { get { return GetCollection<ProduktWykroj>(nameof(ProduktWykrojs)); } }
    }

}
